// This file will be auto-generated by Supabase CLI
// Run: npx supabase gen types typescript --project-id YOUR_PROJECT_ID > src/types/supabase.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          full_name: string | null
          avatar_url: string | null
          phone: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          email: string
          full_name?: string | null
          avatar_url?: string | null
          phone?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          full_name?: string | null
          avatar_url?: string | null
          phone?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      trips: {
        Row: {
          id: string
          name: string
          description: string | null
          destination: string
          start_date: string
          end_date: string
          created_by: string
          created_at: string
          updated_at: string
          status: 'planning' | 'active' | 'completed' | 'cancelled'
          cover_image: string | null
          budget: number | null
          currency: string
        }
        Insert: {
          id?: string
          name: string
          description?: string | null
          destination: string
          start_date: string
          end_date: string
          created_by: string
          created_at?: string
          updated_at?: string
          status?: 'planning' | 'active' | 'completed' | 'cancelled'
          cover_image?: string | null
          budget?: number | null
          currency?: string
        }
        Update: {
          id?: string
          name?: string
          description?: string | null
          destination?: string
          start_date?: string
          end_date?: string
          created_by?: string
          created_at?: string
          updated_at?: string
          status?: 'planning' | 'active' | 'completed' | 'cancelled'
          cover_image?: string | null
          budget?: number | null
          currency?: string
        }
      }
      trip_participants: {
        Row: {
          id: string
          trip_id: string
          user_id: string
          role: 'owner' | 'admin' | 'member'
          joined_at: string
          status: 'pending' | 'accepted' | 'declined'
        }
        Insert: {
          id?: string
          trip_id: string
          user_id: string
          role?: 'owner' | 'admin' | 'member'
          joined_at?: string
          status?: 'pending' | 'accepted' | 'declined'
        }
        Update: {
          id?: string
          trip_id?: string
          user_id?: string
          role?: 'owner' | 'admin' | 'member'
          joined_at?: string
          status?: 'pending' | 'accepted' | 'declined'
        }
      }
      expenses: {
        Row: {
          id: string
          trip_id: string
          amount: number
          currency: string
          category: string
          description: string
          paid_by: string
          created_at: string
          updated_at: string
          receipt_url: string | null
          is_shared: boolean
          split_type: 'equal' | 'percentage' | 'amount' | 'custom'
        }
        Insert: {
          id?: string
          trip_id: string
          amount: number
          currency: string
          category: string
          description: string
          paid_by: string
          created_at?: string
          updated_at?: string
          receipt_url?: string | null
          is_shared?: boolean
          split_type?: 'equal' | 'percentage' | 'amount' | 'custom'
        }
        Update: {
          id?: string
          trip_id?: string
          amount?: number
          currency?: string
          category?: string
          description?: string
          paid_by?: string
          created_at?: string
          updated_at?: string
          receipt_url?: string | null
          is_shared?: boolean
          split_type?: 'equal' | 'percentage' | 'amount' | 'custom'
        }
      }
      expense_splits: {
        Row: {
          id: string
          expense_id: string
          user_id: string
          amount: number
          is_paid: boolean
          paid_at: string | null
        }
        Insert: {
          id?: string
          expense_id: string
          user_id: string
          amount: number
          is_paid?: boolean
          paid_at?: string | null
        }
        Update: {
          id?: string
          expense_id?: string
          user_id?: string
          amount?: number
          is_paid?: boolean
          paid_at?: string | null
        }
      }
      activities: {
        Row: {
          id: string
          trip_id: string
          name: string
          description: string | null
          location: string
          start_time: string
          end_time: string
          created_by: string
          created_at: string
          updated_at: string
          category: string
          cost: number | null
          currency: string | null
        }
        Insert: {
          id?: string
          trip_id: string
          name: string
          description?: string | null
          location: string
          start_time: string
          end_time: string
          created_by: string
          created_at?: string
          updated_at?: string
          category: string
          cost?: number | null
          currency?: string | null
        }
        Update: {
          id?: string
          trip_id?: string
          name?: string
          description?: string | null
          location?: string
          start_time?: string
          end_time?: string
          created_by?: string
          created_at?: string
          updated_at?: string
          category?: string
          cost?: number | null
          currency?: string | null
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

// Additional custom types
export type Trip = Database['public']['Tables']['trips']['Row']
export type User = Database['public']['Tables']['users']['Row']
export type Expense = Database['public']['Tables']['expenses']['Row']
export type Activity = Database['public']['Tables']['activities']['Row']
export type TripParticipant = Database['public']['Tables']['trip_participants']['Row']
export type ExpenseSplit = Database['public']['Tables']['expense_splits']['Row']